[package]
name = "souls-like-death-counter"
version = "0.3.0"
authors = ["Anthony Smith"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Parsing Config File
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
# Decrypt Save File
block-modes = "0.8.1"
aes = "0.7.1"
# Watch Files
crossbeam-channel = "0.4.0"
notify = "4.0.16"
# Get Users Documents Directory
dirs = "3.0"